<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net472</TargetFramework>
    <OutputType>Library</OutputType>
    <LangVersion>default</LangVersion>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)' == 'Release' ">
    <DebugSymbols>true</DebugSymbols>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="0Harmony">
      <HintPath>/home/julian/SecondaryGameLibrary/SteamLibrary/steamapps/common/VTOL VR Mod Loader/Managed/0Harmony.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="ModLoader.Framework">
      <HintPath>/home/julian/SecondaryGameLibrary/SteamLibrary/steamapps/common/VTOL VR Mod Loader/Managed/ModLoader.Framework.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="SteamQueries.Models">
      <HintPath>/home/julian/SecondaryGameLibrary/SteamLibrary/steamapps/common/VTOL VR Mod Loader/Managed/SteamQueries.Models.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="Assembly-CSharp" Publicize="True">
      <HintPath>/home/julian/SecondaryGameLibrary/SteamLibrary/steamapps/common/VTOL VR/VTOLVR_Data/Managed/Assembly-CSharp.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="UnityEngine.AssetBundleModule">
      <HintPath>/home/julian/SecondaryGameLibrary/SteamLibrary/steamapps/common/VTOL VR/VTOLVR_Data/Managed/UnityEngine.AssetBundleModule.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="UnityEngine.CoreModule">
      <HintPath>/home/julian/SecondaryGameLibrary/SteamLibrary/steamapps/common/VTOL VR/VTOLVR_Data/Managed/UnityEngine.CoreModule.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="UnityEngine.IMGUIModule">
      <HintPath>/home/julian/SecondaryGameLibrary/SteamLibrary/steamapps/common/VTOL VR/VTOLVR_Data/Managed/UnityEngine.IMGUIModule.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="UnityEngine.JSONSerializeModule">
      <HintPath>/home/julian/SecondaryGameLibrary/SteamLibrary/steamapps/common/VTOL VR/VTOLVR_Data/Managed/UnityEngine.JSONSerializeModule.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="UnityEngine.ParticleSystemModule">
      <HintPath>/home/julian/SecondaryGameLibrary/SteamLibrary/steamapps/common/VTOL VR/VTOLVR_Data/Managed/UnityEngine.ParticleSystemModule.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="UnityEngine.PhysicsModule">
      <HintPath>/home/julian/SecondaryGameLibrary/SteamLibrary/steamapps/common/VTOL VR/VTOLVR_Data/Managed/UnityEngine.PhysicsModule.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="UnityEngine.UI">
      <HintPath>/home/julian/SecondaryGameLibrary/SteamLibrary/steamapps/common/VTOL VR/VTOLVR_Data/Managed/UnityEngine.UI.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="UnityEngine.UIModule">
      <HintPath>/home/julian/SecondaryGameLibrary/SteamLibrary/steamapps/common/VTOL VR/VTOLVR_Data/Managed/UnityEngine.UIModule.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="UnityEngine.UnityWebRequestAssetBundleModule">
      <HintPath>/home/julian/SecondaryGameLibrary/SteamLibrary/steamapps/common/VTOL VR/VTOLVR_Data/Managed/UnityEngine.UnityWebRequestAssetBundleModule.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="UnityEngine.AudioModule">
      <HintPath>/home/julian/SecondaryGameLibrary/SteamLibrary/steamapps/common/VTOL VR/VTOLVR_Data/Managed/UnityEngine.AudioModule.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="Valve.Newtonsoft.Json">
      <HintPath>/home/julian/SecondaryGameLibrary/SteamLibrary/steamapps/common/VTOL VR/VTOLVR_Data/Managed/Valve.Newtonsoft.Json.dll</HintPath>
      <Private>false</Private>
    </Reference>
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="BepInEx.AssemblyPublicizer.MSBuild" Version="0.4.2">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>
  <Target Name="PostBuild" AfterTargets="PostBuildEvent">
    <Exec Command="cp &quot;$(ProjectDir)item.json&quot; &quot;$(TargetPath)&quot; &quot;$(TargetDir)$(TargetName).pdb&quot; &quot;/home/julian/SecondaryGameLibrary/SteamLibrary/steamapps/common/VTOL VR/@Mod Loader/Mods/LeftThumbstickZoom/&quot;" />
  </Target>
</Project>